# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-02 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='description',
        ),
    ]
