# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-02 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_record_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
